// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3S7A948h5oDJT5xA-hOR-_zv4DZf-ZXY',
    appId: '1:338388910272:web:435ed3411965f1b27fad25',
    messagingSenderId: '338388910272',
    projectId: 'fir-intro-mobile',
    authDomain: 'fir-intro-mobile.firebaseapp.com',
    storageBucket: 'fir-intro-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4FI4F-iaFalhEw5E_jZ8fpyhafPBwILE',
    appId: '1:338388910272:android:f22e1e1ebe82f3057fad25',
    messagingSenderId: '338388910272',
    projectId: 'fir-intro-mobile',
    storageBucket: 'fir-intro-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz6MNiXF3xf81lhnfgW6maQ8Vse7FwXvQ',
    appId: '1:338388910272:ios:7909057ecaca65977fad25',
    messagingSenderId: '338388910272',
    projectId: 'fir-intro-mobile',
    storageBucket: 'fir-intro-mobile.appspot.com',
    iosClientId: '338388910272-vuq3ni1e07nhsctrcenetbsmtdo84paa.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz6MNiXF3xf81lhnfgW6maQ8Vse7FwXvQ',
    appId: '1:338388910272:ios:7909057ecaca65977fad25',
    messagingSenderId: '338388910272',
    projectId: 'fir-intro-mobile',
    storageBucket: 'fir-intro-mobile.appspot.com',
    iosClientId: '338388910272-vuq3ni1e07nhsctrcenetbsmtdo84paa.apps.googleusercontent.com',
    iosBundleId: 'com.example.parkflow',
  );
}
